force-app/main/default/objects/GCP_Notification__c/GCP_Notification__c.object-meta.xml
<CustomObject>
    <label>GCP Notification</label>
    <nameField>
        <displayFormat>GCPN-{00000000}</displayFormat>
        <label>GCP Notification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GCP_Notification__c/fields/Attempts__c.field-meta.xml
<CustomField>
    <fullName>Attempts__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Attempts</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GCP_Notification__c/fields/Optimove_Event_Payload__c.field-meta.xml
<CustomField>
    <fullName>Optimove_Event_Payload__c</fullName>
    <label>Optimove Event Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/GCP_Notification__c/fields/Optimove_Event_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Optimove_Event_Type_Id__c</fullName>
    <label>Optimove Event Type Id</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GCP_Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Optimove_Event__e/Optimove_Event__e.object-meta.xml
<CustomObject>
    <label>Optimove Event</label>
    <pluralLabel>Optimove Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Optimove_Event__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>Optimove event payload</description>
    <label>Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Optimove_Event__e/fields/Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Type_Id__c</fullName>
    <description>Optimove event type id</description>
    <label>Type Id</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OptimoveEventManager.cls
/**
 * @description       :
 * @author            : SkyPlanner - Dianelys Velazquez
 * @group             :
 * @last modified on  : 09-23-2024
 * @last modified by  : SkyPlanner - Dianelys Velazquez
 **/
public with sharing class OptimoveEventManager {
    public static final String GCP_NOTIFICATION_STATUS_PENDING = 'Pending';
    public static final String GCP_NOTIFICATION_STATUS_PROCESSED = 'Processed';
    public static final String GCP_NOTIFICATION_STATUS_FAILED = 'Failed';
    Integer gcpNotifAttemptsLimit = 2;

    public OptimoveEventManager() {
        String limitString = SPGeneralSettings.getInstance()
            .getValue(Constants.GCP_NOTIFICATION_ATTEMPTS_LIMIT);

        if (String.isNotEmpty(limitString) && limitString.isNumeric())
            gcpNotifAttemptsLimit = Integer.valueOf(limitString);
    }

    public void sendGCPNotifications(List<GCP_Notification__c> notifications) {
        Integer i = 0;

        try {
            GCPEventCallout c = new GCPEventCallout();

            for (; i < notifications.size(); i++) {
                GCP_Notification__c notification = notifications[i];

                try {
                    if (notification.Optimove_Event_Type_Id__c == 11)
                        c.notifyEvent11(notification.Optimove_Event_Payload__c);
                    else if (notification.Optimove_Event_Type_Id__c == 13)
                        c.notifyEvent13(notification.Optimove_Event_Payload__c);

                    notification.Status__c = GCP_NOTIFICATION_STATUS_PROCESSED;
                } catch (Exception ex) {
                    onError(ex, notification);
                }
            }
        } catch (Exception ex) {
            for (; i < notifications.size(); i++)
                onError(ex, notifications[i]);
        } finally {
            Database.update(notifications);
        }
    }

    /**
     * @description Publish platform event inmideatly
     * to notify Optimove received event.
     * @author SkyPlanner - Dianelys Velazquez | 09-17-2024
     * @param eventTypeId
     * @param eventPayload
     **/
    public void processEvent(Integer eventTypeId, String eventPayload) {
        Optimove_Event__e event = new Optimove_Event__e();
        event.Type_Id__c = eventTypeId;
        event.Payload__c = eventPayload;

        Database.SaveResult result = EventBus.publish(event);

        if (!result.isSuccess())
            for (Database.Error err : result.getErrors())
                Logger.error(
                    'Error publishing Optimove Event ' + eventTypeId,
                    Constants.LOGGER_OPTIMOVE_API_CATEGORY,
                    'Error: ' + err.getStatusCode() + ' - ' + err.getMessage()
                );
    }

    /**
     * @description Create GCP_Notification__c records
     * from received Optimove_Event__e platform events.
     * @author SkyPlanner - Dianelys Velazquez | 09-17-2024
     * @param events
     **/
    public void processEvents(List<Optimove_Event__e> events) {
        List<GCP_Notification__c> gcpNotifications = new List<GCP_Notification__c>();

        for (Optimove_Event__e event : events)
            gcpNotifications.add(
                new GCP_Notification__c(
                    Optimove_Event_Type_Id__c = event.Type_Id__c,
                    Optimove_Event_Payload__c = event.Payload__c
                )
            );

        DataBase.SaveResult[] saveResults = Database.insert(
            gcpNotifications,
            false
        );

        logErrors(saveResults);
        scheduleGCPNotificationBatches();
    }

    public void scheduleGCPNotificationBatches() {
        BatchOrderManager mng = new BatchOrderManager(
            new List<GenericBatch>{
                new GCPNotificationBatch(),
                new GCPNotificationDeleteBatch()
            }
        );
        mng.executeNext();
    }

    void logErrors(List<Database.SaveResult> saveResults) {
        for (Database.SaveResult sr : saveResults) {
            if (!sr.isSuccess()) {
                for (Database.Error err : sr.getErrors()) {
                    Logger.error(
                        'Error inserting GCP Notification',
                        Constants.LOGGER_OPTIMOVE_API_CATEGORY,
                        'Error: ' +
                            err.getStatusCode() +
                            ' - ' +
                            err.getMessage()
                    );
                }
            }
        }
    }

    void onError(Exception ex, GCP_Notification__c n) {
        n.Attempts__c++;
        n.Error_Message__c = ex.getMessage();

        if (n.Attempts__c >= gcpNotifAttemptsLimit)
            n.Status__c = GCP_NOTIFICATION_STATUS_FAILED;
    }
}