force-app/main/default/objects/GCP_Notification__c/GCP_Notification__c.object-meta.xml
<CustomObject>
    <label>GCP Notification</label>
    <nameField>
        <displayFormat>GCPN-{00000000}</displayFormat>
        <label>GCP Notification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GCP_Notification__c/fields/Attempts__c.field-meta.xml
<CustomField>
    <fullName>Attempts__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Attempts</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GCP_Notification__c/fields/Optimove_Event_Payload__c.field-meta.xml
<CustomField>
    <fullName>Optimove_Event_Payload__c</fullName>
    <label>Optimove Event Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/GCP_Notification__c/fields/Optimove_Event_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Optimove_Event_Type_Id__c</fullName>
    <label>Optimove Event Type Id</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GCP_Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GCPNotificationBatch.cls
/**
 * @description       :
 * @author            : SkyPlanner - Dianelys Velazquez
 * @group             :
 * @last modified on  : 09-17-2024
 * @last modified by  : SkyPlanner - Dianelys Velazquez
 **/
public with sharing class GCPNotificationBatch extends GenericBatch {
    public override Integer getBatchSize() {
        return 1;
    }

    public override String getQuery() {
        return 'SELECT Optimove_Event_Type_Id__c, ' +
            'Optimove_Event_Payload__c, ' +
            'Status__c, ' +
            'Attempts__c, ' +
            'Error_Message__c ' +
            'FROM GCP_Notification__c ' +
            'WHERE Status__c = \'' +
            OptimoveEventManager.GCP_NOTIFICATION_STATUS_PENDING +
            '\'';
    }

    public override void execute(List<SObject> scope) {
        OptimoveEventManager mng = new OptimoveEventManager();
        mng.sendGCPNotifications((List<GCP_Notification__c>) scope);
    }
}