force-app/main/default/objects/GCP_Notification__c/GCP_Notification__c.object-meta.xml
<CustomObject>
    <label>GCP Notification</label>
    <nameField>
        <displayFormat>GCPN-{00000000}</displayFormat>
        <label>GCP Notification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GCP_Notification__c/fields/Attempts__c.field-meta.xml
<CustomField>
    <fullName>Attempts__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Attempts</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GCP_Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GCPNotificationDeleteBatchTest.cls
/**
 * @description       :
 * @author            : SkyPlanner - Dianelys Velazquez
 * @group             :
 * @last modified on  : 10-03-2024
 * @last modified by  : SkyPlanner - Dianelys Velazquez
 **/
@isTest
private class GCPNotificationDeleteBatchTest {
    @isTest
    static void notifyEvent11SuccessTest() {
        OptimoveTestData.getNotifications(150, true);

        Test.startTest();

        new GCPNotificationDeleteBatch().executeBatch();

        Test.stopTest();

        List<GCP_Notification__c> notifications = [
            SELECT Status__c, Attempts__c
            FROM GCP_Notification__c
        ];

        Assert.isTrue(
            notifications.isEmpty(),
            'Notifications should be empty.'
        );
    }
}