force-app/main/default/objects/GCP_Notification__c/GCP_Notification__c.object-meta.xml
<CustomObject>
    <label>GCP Notification</label>
    <nameField>
        <displayFormat>GCPN-{00000000}</displayFormat>
        <label>GCP Notification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GCP_Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GCPNotificationDeleteBatch.cls
/**
 * @description       :
 * @author            : SkyPlanner - Dianelys Velazquez
 * @group             :
 * @last modified on  : 09-17-2024
 * @last modified by  : SkyPlanner - Dianelys Velazquez
 **/
public with sharing class GCPNotificationDeleteBatch extends DeleteRecordBatch {
    public override String getQuery() {
        return 'SELECT Id ' +
            'FROM GCP_Notification__c ' +
            'WHERE Status__c = \'' +
            OptimoveEventManager.GCP_NOTIFICATION_STATUS_PROCESSED +
            '\'';
    }
}