force-app/main/default/objects/GCP_Notification__c/GCP_Notification__c.object-meta.xml
<CustomObject>
    <label>GCP Notification</label>
    <nameField>
        <displayFormat>GCPN-{00000000}</displayFormat>
        <label>GCP Notification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GCP Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GCP_Notification__c/fields/Optimove_Event_Payload__c.field-meta.xml
<CustomField>
    <fullName>Optimove_Event_Payload__c</fullName>
    <label>Optimove Event Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/GCP_Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OptimoveEvent11CallbackTest.cls
/**
 * @description       :
 * @author            : SkyPlanner - Dianelys Velazquez
 * @group             :
 * @last modified on  : 10-03-2024
 * @last modified by  : SkyPlanner - Dianelys Velazquez
 **/
@isTest
class OptimoveEvent11CallbackTest {
    @isTest
    public static void receivingEvent11FromOptimoveTest() {
        RestRequest req = new RestRequest();
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf('abc');
        RestResponse res = new RestResponse();

        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();

        OptimoveEvent11Callback.doPost();

        Test.stopTest();

        List<GCP_Notification__c> notifications = [
            SELECT Optimove_Event_Payload__c, Status__c
            FROM GCP_Notification__c
        ];

        Assert.areEqual(200, res.statusCode, 'Status code should be 200.');
        Assert.areEqual(1, notifications.size(), 'Should be 1 notification');
        Assert.areEqual(
            'Pending',
            notifications[0].Status__c,
            'Invalid status'
        );
        Assert.areEqual(
            'abc',
            notifications[0].Optimove_Event_Payload__c,
            'Invalid payload'
        );
    }
}